export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ITIATE_RESET_SUCCESS = "ITIATE_RESET_SUCCESS";
export const ITIATE_RESET_FAIL = "ITIATE_RESET_FAIL";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILED = "RESET_FAILED";
export const LOADING = "LOADING";